name: Rules  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /rules get lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-g.zip rules/get/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-g
            zip_file: m-s-rules-g.zip
      - name: /rules post lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-po.zip rules/post/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-po
            zip_file: m-s-rules-po.zip
      - name: /rules/{rule_id} get lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-g.zip rules/rule_id/get/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-g
            zip_file: m-s-rules-rule-g.zip
      - name: /rules/{rule_id} put lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-pu.zip rules/rule_id/put/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-pu
            zip_file: m-s-rules-rule-pu.zip
      - name: /rules/{rule_id} delete lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-d.zip rules/rule_id/delete/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-d
            zip_file: m-s-rules-rule-d.zip          
      - name: /rules/{rule_id}/tags get lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-tags-g.zip rules/rule_id/tags/get/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-tags-g
            zip_file: m-s-rules-rule-tags-g.zip
      - name: /rules/{rule_id}/tags post lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-tags-po.zip rules/rule_id/tags/post/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-tags-po
            zip_file: m-s-rules-rule-tags-po.zip
      - name: /rules/{rule_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/rules@main
        with:
            args: zip -qq -r m-s-rules-rule-tags-tag-d.zip rules/rule_id/tags/tag_id/delete/index.js node_modules
      - name: rules get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-rules-rule-tags-tag-d
            zip_file: m-s-rules-rule-tags-tag-d.zip            